
["Configs for Curios Back Weapon Slot"]
	#Whetever to show the weapon back slot or not beside the hotbar
	show_back_weapon = true
	#Move the weapon back slot (the one that is near the hotbar) along the X axis
	x_offset = 0
	#Move the weapon back slot (the one that is near the hotbar) along the Y axis
	Y_offset = 0

